spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random

    gateway:
      routes:
        - id: userService
          uri: http://localhost:8081/
          predicates:

            - Path=/user-service/**
        - id: vehicleService
          uri: http://localhost:8083/
          predicates:
            - Path=/vehicle-service/**
        - id: parkingService
          uri: http://localhost:8084/
          predicates:
            - Path=/parking-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D"

